#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <access_token> <artist_id>"
    exit 1
fi

access_token=$1
artist_id=$2

artist=$(curl --fail --silent --request GET \
  --url https://api.spotify.com/v1/artists/$artist_id \
  --header "Authorization: Bearer $access_token")

name=$(echo -n "$artist" | jq -r '.name')
images=$(echo -n "$artist" | jq -r '.images')

json_string=$(jq -n -c --arg name "$name" --argjson images "$images" '{name: $name, images: $images}')

echo -n $json_string
